[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
anyhow.workspace = true
common.workspace = true
derive-new.workspace = true
serde.workspace = true
csv.workspace = true
