[package]
name = "registry"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
shaku.workspace = true
data_access.workspace = true
service.workspace = true
common.workspace = true
