[package]
name = "testapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
uuid = { version = "^1.11", features = ["v4", "fast-rng", "macro-diagnostics"] }
dotenvy = { version = "0.15.7" }
axum = { version = "0.7.9", features = ["macros", "http2", "multipart", "ws"] }
axum-extra = { version = "0.9.6", features = [
    "cookie",
    "cookie-private",
    "typed-header",
    "multipart",
] }
tower = "0.5.1"
tower-http = { version = "^0.6", features = ["trace", "cors"] }
tokio = { version = "^1.41.1", features = ["full"] }
sqlx = { version = "^0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "chrono",
    "sqlite",
] }
serde = { version = "^1.0.215", features = ["derive"] }
serde_json = "^1.0.133"
serde_repr = "^0.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
chrono = { version = "0.4.34", features = ["serde"] }
chrono-tz = { version = "^0.10", features = ["filter-by-regex", "serde"] }
csv = "1.3.1"
