[package]
name = "sotaapp2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/bin/app.rs"

[workspace]
members = ["web_api", "service", "data_access", "common", "registry", "domain"]

[workspace.dependencies]
domain = { path = "./domain" }
common = { path = "./common" }
web_api = { path = "./web_api" }
service = { path = "./service" }
data_access = { path = "./data_access" }
registry = { path = "./registry" }

anyhow = "1.0.94"
derive-new = "0.7.0"
uuid = { version = "^1.11", features = ["v4", "fast-rng", "macro-diagnostics"] }
async-trait = "0.1.83"
axum = { version = "0.7.9", features = ["macros", "http2", "multipart", "ws"] }
axum-extra = { version = "0.9.6", features = [
    "cookie",
    "cookie-private",
    "typed-header",
    "multipart",
] }
tower = "0.5.1"
tower-http = { version = "^0.6", features = ["trace", "cors"] }
tokio = { version = "^1.41.1", features = ["full"] }
sqlx = { version = "^0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "chrono",
    "postgres",
    "macros",
    "migrate",
] }
serde = { version = "^1.0.215", features = ["derive"] }
serde_json = "^1.0.133"
serde_repr = "^0.1"
thiserror = "2.0.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
chrono = { version = "0.4.34", features = ["serde"] }
chrono-tz = { version = "^0.10", features = ["filter-by-regex", "serde"] }
csv = "1.3.1"
rstest = "0.23.0"
shaku = "0.6.2"
shaku_axum = "0.5.0"

[dependencies]
web_api.workspace = true
service.workspace = true
common.workspace = true
domain.workspace = true
data_access.workspace = true
registry.workspace = true
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
shaku_axum.workspace = true
