FROM rust:1.83-slim-bookworm AS builder
WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
RUN apt update && apt install -y libssl-dev &&  apt install -y pkg-config && apt install -y sqlite3 && apt install -y wget
COPY . .
COPY adapter/migrations/sqlite migrations/
RUN mkdir ./data && sqlite3 ./data/sotaapp2.db < ./migrations/20241130234000_start.up.sql
RUN cargo build --release

FROM debian:bookworm-slim
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
RUN apt update && apt install -y libssl-dev &&  apt install -y pkg-config && apt install -y sqlite3 && apt install -y wget
WORKDIR /app
COPY --from=builder ./app/target/release/app ./target/release/app
COPY static/ static/
COPY adapter/migrations/sqlite migrations/
RUN mkdir -p /app/data
RUN adduser admin && chown -R admin /app
USER admin
ENTRYPOINT ["./target/release/app"]
