[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
derive-new.workspace = true
csv.workspace = true
serde.workspace = true
common.workspace = true
shaku.workspace = true
sqlx.workspace = true
