[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
axum.workspace = true
csv.workspace = true
application.workspace = true
registry.workspace = true
common.workspace = true
