[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
registry.workspace = true
serde.workspace = true
axum.workspace = true
application.workspace = true
geo-types.workspace = true
common.workspace = true
