[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
axum.workspace = true
service.workspace = true
registry.workspace = true
common.workspace = true
domain.workspace = true
shaku_axum.workspace = true
